// Package generator emits Valid methods for string-backed enum types.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/godexture/godec/tools/internal/cli"
	"github.com/godexture/godec/tools/internal/enumscan"
)

// Generate writes a Valid() bool method for each enum to output.
func Generate(output, packageName string, enums []enumscan.Enum) {
	absOutput, _ := filepath.Abs(output)
	if absOutput == "" {
		absOutput = output
	}
	log.Printf("generating %s...", absOutput)
	defer log.Printf("generated %s", absOutput)

	var body bytes.Buffer
	fmt.Fprintf(&body, "// Code generated by enum-generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&body, "package %s\n\n", packageName)

	for _, enum := range enums {
		fmt.Fprintf(&body, "func (v %s) Valid() bool {\n\tswitch v {\n\tcase %s:\n\t\treturn true\n\t}\n\treturn false\n}\n\n", enum.TypeName, quoted(enum.Values))
	}

	formatted, err := format.Source(body.Bytes())
	if err != nil {
		fmt.Println(body.String())
		cli.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(output, formatted, 0644); err != nil {
		cli.Fatalf("write %s: %v", output, err)
	}
}

func quoted(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = fmt.Sprintf("%q", value)
	}
	return strings.Join(quoted, ", ")
}
