package diagnostic_test

import (
	"errors"
	"strings"
	"testing"

	"github.com/godexture/godec/diagnostic"
)

type secretString string

func (s secretString) Error() string { return string(s) }

// A panic value belongs to the code that panicked, so it can be the credential
// that code was handling. Rendering it puts the credential in every diagnostic,
// Result, and log line that quotes the recovered value.
func TestRecoveredNeverRendersACallerChosenValue(t *testing.T) {
	const secret = "r01-panic-secret"
	for _, value := range []any{
		secret,
		errors.New(secret),
		secretString(secret),
		[]string{secret},
		map[string]string{"token": secret},
		struct{ Token string }{Token: secret},
		&struct{ Token string }{Token: secret},
	} {
		if got := diagnostic.Recovered(value); strings.Contains(got, secret) {
			t.Errorf("Recovered(%T) = %q, which exposes the panic value", value, got)
		}
	}
}

// A runtime error is generated by Go and carries no caller data, so keeping
// its message costs nothing and is what usually explains the panic.
func TestRecoveredKeepsRuntimeErrors(t *testing.T) {
	recovered := func() (value any) {
		defer func() { value = recover() }()
		var values []int
		_ = values[1]
		return nil
	}()
	if got := diagnostic.Recovered(recovered); !strings.Contains(got, "out of range") {
		t.Errorf("Recovered(runtime error) = %q, want the runtime message", got)
	}
	if got := diagnostic.Recovered(nil); got == "" {
		t.Error("Recovered(nil) produced no description")
	}
}
