// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	internal "github.com/godexture/format-flac/internal"
)

type DemuxerConfig internal.DemuxerConfig

type DemuxerConfigOption func(*DemuxerConfig)

func NewDemuxerConfig(options ...DemuxerConfigOption) DemuxerConfig {
	config := DemuxerConfig(internal.DemuxerConfig{})
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithStrict(v bool) DemuxerConfigOption {
	return func(c *DemuxerConfig) {
		c.Strict = v
	}
}

func (c DemuxerConfig) ResolveDefault() internal.DemuxerConfig {
	return internal.DemuxerConfig{}
}

func (c DemuxerConfig) Resolve() internal.DemuxerConfig {
	return internal.DemuxerConfig(c)
}
