// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	config "github.com/godexture/codec-flac/internal/config"
	flac "github.com/godexture/codec-flac/internal/flac"
)

type EncoderConfig config.EncoderConfig

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	config := EncoderConfig(config.DefaultEncoderConfig)
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithSampleRate(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.SampleRate = v
	}
}

func WithChannels(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Channels = v
	}
}

func WithBitsPerSample(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BitsPerSample = v
	}
}

func WithBlockSize(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSize = v
	}
}

func WithMaxFixedOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxFixedOrder = v
	}
}

func WithMaxLPCOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxLPCOrder = v
	}
}

func WithMaxRicePartitionOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxRicePartitionOrder = v
	}
}

func WithLPCPrecision(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.LPCPrecision = v
	}
}

func WithEnablePrecisionSearch(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.EnablePrecisionSearch = v
	}
}

func WithEnableWastedBits(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.EnableWastedBits = v
	}
}

func WithStereoMode(v StereoMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.StereoMode = v
	}
}

func WithFixedOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.FixedOrderSearch = v
	}
}

func WithLPCOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.LPCOrderSearch = v
	}
}

func WithRiceCost(v RiceCostMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.RiceCost = v
	}
}

func WithApodizations(v []flac.Apodization) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Apodizations = v
	}
}

func WithBlockSplitDepth(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSplitDepth = v
	}
}

func WithBlockSplitMode(v BlockSplitMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSplitMode = v
	}
}

func WithStreamableSubset(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.StreamableSubset = v
	}
}

func WithWorkers(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Workers = v
	}
}

func WithPreset(level int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		*c = EncoderConfig(config.GetPreset(normalizeCompressionLevel(level)))
	}
}

func (c EncoderConfig) ResolveDefault() config.EncoderConfig {
	return config.DefaultEncoderConfig
}

func (c EncoderConfig) Resolve() config.EncoderConfig {
	return config.EncoderConfig(c)
}
