// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	domain "github.com/godexture/codec-mp3/internal/domain"
	optional "github.com/godexture/sdk/optional"
)

type EncoderConfig struct {
	Bitrate optional.Optional[int]
}

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	var config EncoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithBitrate(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Bitrate = optional.Some(v)
	}
}

func (c EncoderConfig) ApplyDefaults() domain.EncoderConfig {
	config := domain.DefaultEncoderConfig
	config.Bitrate = c.Bitrate.ValueOr(config.Bitrate)
	return config
}
