// Code generated by config-generator. DO NOT EDIT.

package filter

import (
	media "github.com/godexture/core/domain/media"
	config "github.com/godexture/filter-audio/internal/config"
	time "time"
)

type FormatConfig config.FormatConfig

type FormatConfigOption interface {
	applyFormatConfig(*FormatConfig)
}

type formatConfigOptionFunc func(*FormatConfig)

func (f formatConfigOptionFunc) applyFormatConfig(c *FormatConfig) {
	f(c)
}

func NewFormatConfig(options ...FormatConfigOption) FormatConfig {
	config := FormatConfig(config.DefaultFormatConfig)
	for _, option := range options {
		option.applyFormatConfig(&config)
	}
	return config
}

func (c FormatConfig) ResolveDefault() config.FormatConfig {
	return config.FormatConfig(config.DefaultFormatConfig)
}

func (c FormatConfig) Resolve() config.FormatConfig {
	return config.FormatConfig(c)
}

func (c FormatConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c FormatConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type ResampleConfig config.ResampleConfig

type ResampleConfigOption interface {
	applyResampleConfig(*ResampleConfig)
}

type resampleConfigOptionFunc func(*ResampleConfig)

func (f resampleConfigOptionFunc) applyResampleConfig(c *ResampleConfig) {
	f(c)
}

func NewResampleConfig(options ...ResampleConfigOption) ResampleConfig {
	config := ResampleConfig(config.DefaultResampleConfig)
	for _, option := range options {
		option.applyResampleConfig(&config)
	}
	return config
}

func (c ResampleConfig) ResolveDefault() config.ResampleConfig {
	return config.ResampleConfig(config.DefaultResampleConfig)
}

func (c ResampleConfig) Resolve() config.ResampleConfig {
	return config.ResampleConfig(c)
}

func (c ResampleConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c ResampleConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type RemixConfig config.RemixConfig

type RemixConfigOption interface {
	applyRemixConfig(*RemixConfig)
}

type remixConfigOptionFunc func(*RemixConfig)

func (f remixConfigOptionFunc) applyRemixConfig(c *RemixConfig) {
	f(c)
}

func NewRemixConfig(options ...RemixConfigOption) RemixConfig {
	config := RemixConfig(config.DefaultRemixConfig)
	for _, option := range options {
		option.applyRemixConfig(&config)
	}
	return config
}

func (c RemixConfig) ResolveDefault() config.RemixConfig {
	return config.RemixConfig(config.DefaultRemixConfig)
}

func (c RemixConfig) Resolve() config.RemixConfig {
	return config.RemixConfig(c)
}

func (c RemixConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c RemixConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type GainConfig config.GainConfig

type GainConfigOption interface {
	applyGainConfig(*GainConfig)
}

type gainConfigOptionFunc func(*GainConfig)

func (f gainConfigOptionFunc) applyGainConfig(c *GainConfig) {
	f(c)
}

func NewGainConfig(options ...GainConfigOption) GainConfig {
	config := GainConfig(config.DefaultGainConfig)
	for _, option := range options {
		option.applyGainConfig(&config)
	}
	return config
}

func (c GainConfig) ResolveDefault() config.GainConfig {
	return config.GainConfig(config.DefaultGainConfig)
}

func (c GainConfig) Resolve() config.GainConfig {
	return config.GainConfig(c)
}

func (c GainConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c GainConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type NormalizeConfig config.NormalizeConfig

type NormalizeConfigOption interface {
	applyNormalizeConfig(*NormalizeConfig)
}

type normalizeConfigOptionFunc func(*NormalizeConfig)

func (f normalizeConfigOptionFunc) applyNormalizeConfig(c *NormalizeConfig) {
	f(c)
}

func NewNormalizeConfig(options ...NormalizeConfigOption) NormalizeConfig {
	config := NormalizeConfig(config.DefaultNormalizeConfig)
	for _, option := range options {
		option.applyNormalizeConfig(&config)
	}
	return config
}

func (c NormalizeConfig) ResolveDefault() config.NormalizeConfig {
	return config.NormalizeConfig(config.DefaultNormalizeConfig)
}

func (c NormalizeConfig) Resolve() config.NormalizeConfig {
	return config.NormalizeConfig(c)
}

func (c NormalizeConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c NormalizeConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type FadeConfig config.FadeConfig

type FadeConfigOption interface {
	applyFadeConfig(*FadeConfig)
}

type fadeConfigOptionFunc func(*FadeConfig)

func (f fadeConfigOptionFunc) applyFadeConfig(c *FadeConfig) {
	f(c)
}

func NewFadeConfig(options ...FadeConfigOption) FadeConfig {
	config := FadeConfig(config.DefaultFadeConfig)
	for _, option := range options {
		option.applyFadeConfig(&config)
	}
	return config
}

func (c FadeConfig) ResolveDefault() config.FadeConfig {
	return config.FadeConfig(config.DefaultFadeConfig)
}

func (c FadeConfig) Resolve() config.FadeConfig {
	return config.FadeConfig(c)
}

func (c FadeConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c FadeConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type DCOffsetConfig config.DCOffsetConfig

type DCOffsetConfigOption interface {
	applyDCOffsetConfig(*DCOffsetConfig)
}

type dCOffsetConfigOptionFunc func(*DCOffsetConfig)

func (f dCOffsetConfigOptionFunc) applyDCOffsetConfig(c *DCOffsetConfig) {
	f(c)
}

func NewDCOffsetConfig(options ...DCOffsetConfigOption) DCOffsetConfig {
	config := DCOffsetConfig(config.DefaultDCOffsetConfig)
	for _, option := range options {
		option.applyDCOffsetConfig(&config)
	}
	return config
}

func (c DCOffsetConfig) ResolveDefault() config.DCOffsetConfig {
	return config.DCOffsetConfig(config.DefaultDCOffsetConfig)
}

func (c DCOffsetConfig) Resolve() config.DCOffsetConfig {
	return config.DCOffsetConfig(c)
}

func (c DCOffsetConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c DCOffsetConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type TrimConfig config.TrimConfig

type TrimConfigOption interface {
	applyTrimConfig(*TrimConfig)
}

type trimConfigOptionFunc func(*TrimConfig)

func (f trimConfigOptionFunc) applyTrimConfig(c *TrimConfig) {
	f(c)
}

func NewTrimConfig(options ...TrimConfigOption) TrimConfig {
	config := TrimConfig(config.DefaultTrimConfig)
	for _, option := range options {
		option.applyTrimConfig(&config)
	}
	return config
}

func (c TrimConfig) ResolveDefault() config.TrimConfig {
	return config.TrimConfig(config.DefaultTrimConfig)
}

func (c TrimConfig) Resolve() config.TrimConfig {
	return config.TrimConfig(c)
}

func (c TrimConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c TrimConfig) FieldChoices(field string) []string {
	switch field {
	case "TrimMode":
		return []string{"both", "start", "end"}
	default:
		return nil
	}
}

type SpeedConfig config.SpeedConfig

type SpeedConfigOption interface {
	applySpeedConfig(*SpeedConfig)
}

type speedConfigOptionFunc func(*SpeedConfig)

func (f speedConfigOptionFunc) applySpeedConfig(c *SpeedConfig) {
	f(c)
}

func NewSpeedConfig(options ...SpeedConfigOption) SpeedConfig {
	config := SpeedConfig(config.DefaultSpeedConfig)
	for _, option := range options {
		option.applySpeedConfig(&config)
	}
	return config
}

func (c SpeedConfig) ResolveDefault() config.SpeedConfig {
	return config.SpeedConfig(config.DefaultSpeedConfig)
}

func (c SpeedConfig) Resolve() config.SpeedConfig {
	return config.SpeedConfig(c)
}

func (c SpeedConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c SpeedConfig) FieldChoices(field string) []string {
	switch field {
	case "Mode":
		return []string{"interpolate", "relabel"}
	default:
		return nil
	}
}

type CompressorConfig config.CompressorConfig

type CompressorConfigOption interface {
	applyCompressorConfig(*CompressorConfig)
}

type compressorConfigOptionFunc func(*CompressorConfig)

func (f compressorConfigOptionFunc) applyCompressorConfig(c *CompressorConfig) {
	f(c)
}

func NewCompressorConfig(options ...CompressorConfigOption) CompressorConfig {
	config := CompressorConfig(config.DefaultCompressorConfig)
	for _, option := range options {
		option.applyCompressorConfig(&config)
	}
	return config
}

func (c CompressorConfig) ResolveDefault() config.CompressorConfig {
	return config.CompressorConfig(config.DefaultCompressorConfig)
}

func (c CompressorConfig) Resolve() config.CompressorConfig {
	return config.CompressorConfig(c)
}

func (c CompressorConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c CompressorConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

type EQConfig config.EQConfig

type EQConfigOption interface {
	applyEQConfig(*EQConfig)
}

type eQConfigOptionFunc func(*EQConfig)

func (f eQConfigOptionFunc) applyEQConfig(c *EQConfig) {
	f(c)
}

func NewEQConfig(options ...EQConfigOption) EQConfig {
	config := EQConfig(config.DefaultEQConfig)
	for _, option := range options {
		option.applyEQConfig(&config)
	}
	return config
}

func (c EQConfig) ResolveDefault() config.EQConfig {
	return config.EQConfig(config.DefaultEQConfig)
}

func (c EQConfig) Resolve() config.EQConfig {
	return config.EQConfig(c)
}

func (c EQConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c EQConfig) FieldChoices(field string) []string {
	switch field {
	case "Type":
		return []string{"peaking", "lowshelf", "highshelf", "lowpass", "highpass"}
	default:
		return nil
	}
}

func WithFormat(v media.SampleFormat) FormatConfigOption {
	return formatConfigOptionFunc(func(c *FormatConfig) {
		c.Format = v
	})
}

func WithBitsPerSample(v int) FormatConfigOption {
	return formatConfigOptionFunc(func(c *FormatConfig) {
		c.BitsPerSample = v
	})
}

func WithSampleRate(v int) ResampleConfigOption {
	return resampleConfigOptionFunc(func(c *ResampleConfig) {
		c.SampleRate = v
	})
}

func WithLayout(v media.ChannelLayout) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.Layout = v
	})
}

func WithCenterMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.CenterMixDB = v
	})
}

func WithSurroundMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.SurroundMixDB = v
	})
}

func WithLFEMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.LFEMixDB = v
	})
}

func WithNormalize(v bool) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.Normalize = v
	})
}

func WithDecibels(v float64) GainConfigOption {
	return gainConfigOptionFunc(func(c *GainConfig) {
		c.Decibels = v
	})
}

func WithTargetPeakDBFS(v float64) NormalizeConfigOption {
	return normalizeConfigOptionFunc(func(c *NormalizeConfig) {
		c.TargetPeakDBFS = v
	})
}

func WithAllowAmplification(v bool) NormalizeConfigOption {
	return normalizeConfigOptionFunc(func(c *NormalizeConfig) {
		c.AllowAmplification = v
	})
}

type MemoryLimitBytesOption interface {
	NormalizeConfigOption
	FadeConfigOption
	TrimConfigOption
}

type memoryLimitBytesOpt struct{ v int64 }

func (o memoryLimitBytesOpt) applyNormalizeConfig(c *NormalizeConfig) {
	c.MemoryLimitBytes = o.v
}
func (o memoryLimitBytesOpt) applyFadeConfig(c *FadeConfig) {
	c.MemoryLimitBytes = o.v
}
func (o memoryLimitBytesOpt) applyTrimConfig(c *TrimConfig) {
	c.MemoryLimitBytes = o.v
}

func WithMemoryLimitBytes(v int64) MemoryLimitBytesOption {
	return memoryLimitBytesOpt{v}
}

type TempDirOption interface {
	NormalizeConfigOption
	FadeConfigOption
	TrimConfigOption
}

type tempDirOpt struct{ v string }

func (o tempDirOpt) applyNormalizeConfig(c *NormalizeConfig) {
	c.TempDir = o.v
}
func (o tempDirOpt) applyFadeConfig(c *FadeConfig) {
	c.TempDir = o.v
}
func (o tempDirOpt) applyTrimConfig(c *TrimConfig) {
	c.TempDir = o.v
}

func WithTempDir(v string) TempDirOption {
	return tempDirOpt{v}
}

func WithFadeIn(v time.Duration) FadeConfigOption {
	return fadeConfigOptionFunc(func(c *FadeConfig) {
		c.FadeIn = v
	})
}

func WithFadeOut(v time.Duration) FadeConfigOption {
	return fadeConfigOptionFunc(func(c *FadeConfig) {
		c.FadeOut = v
	})
}

func WithPole(v float64) DCOffsetConfigOption {
	return dCOffsetConfigOptionFunc(func(c *DCOffsetConfig) {
		c.Pole = v
	})
}

type ThresholdDBFSOption interface {
	TrimConfigOption
	CompressorConfigOption
}

type thresholdDBFSOpt struct{ v float64 }

func (o thresholdDBFSOpt) applyTrimConfig(c *TrimConfig) {
	c.ThresholdDBFS = o.v
}
func (o thresholdDBFSOpt) applyCompressorConfig(c *CompressorConfig) {
	c.ThresholdDBFS = o.v
}

func WithThresholdDBFS(v float64) ThresholdDBFSOption {
	return thresholdDBFSOpt{v}
}

func WithTrimMode(v TrimMode) TrimConfigOption {
	return trimConfigOptionFunc(func(c *TrimConfig) {
		c.TrimMode = v
	})
}

func WithApproximateSilence(v bool) TrimConfigOption {
	return trimConfigOptionFunc(func(c *TrimConfig) {
		c.ApproximateSilence = v
	})
}

func WithFactor(v float64) SpeedConfigOption {
	return speedConfigOptionFunc(func(c *SpeedConfig) {
		c.Factor = v
	})
}

func WithMode(v SpeedMode) SpeedConfigOption {
	return speedConfigOptionFunc(func(c *SpeedConfig) {
		c.Mode = v
	})
}

func WithRatio(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.Ratio = v
	})
}

func WithAttackMs(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.AttackMs = v
	})
}

func WithReleaseMs(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.ReleaseMs = v
	})
}

func WithKneeDB(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.KneeDB = v
	})
}

func WithMakeupGainDB(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.MakeupGainDB = v
	})
}

func WithType(v EQType) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.Type = v
	})
}

func WithFrequencyHz(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.FrequencyHz = v
	})
}

func WithGainDB(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.GainDB = v
	})
}

func WithQ(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.Q = v
	})
}
