// Code generated by config-generator. DO NOT EDIT.

package pcm

import (
	binary "encoding/binary"
	internal "github.com/godexture/codec-pcm/internal"
	media "github.com/godexture/core/domain/media"
	params "github.com/godexture/format-wav/params"
	optional "github.com/godexture/sdk/optional"
)

type EncoderConfig struct {
	CodecID   optional.Optional[media.CodecID]
	ByteOrder optional.Optional[binary.ByteOrder]
	ADPCM     optional.Optional[params.ADPCM]
}

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	var config EncoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithCodecID(v media.CodecID) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.CodecID = optional.Some(v)
	}
}

func WithByteOrder(v binary.ByteOrder) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.ByteOrder = optional.Some(v)
	}
}

func WithADPCM(v params.ADPCM) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.ADPCM = optional.Some(v)
	}
}

func (c EncoderConfig) ApplyDefaults() internal.EncoderConfig {
	config := internal.DefaultEncoderConfig
	config.CodecID = c.CodecID.ValueOr(config.CodecID)
	config.ByteOrder = c.ByteOrder.ValueOr(config.ByteOrder)
	config.ADPCM = c.ADPCM.ValueOr(config.ADPCM)
	return config
}
