// Code generated by config-generator. DO NOT EDIT.

package pcm

import (
	binary "encoding/binary"
	internal "github.com/godexture/codec-pcm/internal"
)

type DecoderConfig internal.DecoderConfig

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config := DecoderConfig(internal.DefaultDecoderConfig)
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithByteOrder(v binary.ByteOrder) DecoderConfigOption {
	return func(c *DecoderConfig) {
		c.ByteOrder = v
	}
}

func (c DecoderConfig) ResolveDefault() internal.DecoderConfig {
	return internal.DefaultDecoderConfig
}

func (c DecoderConfig) Resolve() internal.DecoderConfig {
	return internal.DecoderConfig(c)
}
