// Code generated by config-generator. DO NOT EDIT.

package pcm

import (
	binary "encoding/binary"
	internal "github.com/godexture/codec-pcm/internal"
	media "github.com/godexture/core/domain/media"
	params "github.com/godexture/format-wav/params"
)

type EncoderConfig internal.EncoderConfig

type EncoderConfigOption interface {
	applyEncoderConfig(*EncoderConfig)
}

type encoderConfigOptionFunc func(*EncoderConfig)

func (f encoderConfigOptionFunc) applyEncoderConfig(c *EncoderConfig) {
	f(c)
}

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	config := EncoderConfig(internal.DefaultEncoderConfig)
	for _, option := range options {
		option.applyEncoderConfig(&config)
	}
	return config
}

func (c EncoderConfig) ResolveDefault() internal.EncoderConfig {
	return internal.EncoderConfig(internal.DefaultEncoderConfig)
}

func (c EncoderConfig) Resolve() internal.EncoderConfig {
	return internal.EncoderConfig(c)
}

func (c EncoderConfig) Validate() error {
	return nil
}

type DecoderConfig internal.DecoderConfig

type DecoderConfigOption interface {
	applyDecoderConfig(*DecoderConfig)
}

type decoderConfigOptionFunc func(*DecoderConfig)

func (f decoderConfigOptionFunc) applyDecoderConfig(c *DecoderConfig) {
	f(c)
}

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config := DecoderConfig(internal.DefaultDecoderConfig)
	for _, option := range options {
		option.applyDecoderConfig(&config)
	}
	return config
}

func (c DecoderConfig) ResolveDefault() internal.DecoderConfig {
	return internal.DecoderConfig(internal.DefaultDecoderConfig)
}

func (c DecoderConfig) Resolve() internal.DecoderConfig {
	return internal.DecoderConfig(c)
}

func (c DecoderConfig) Validate() error {
	return nil
}

func WithCodecID(v media.CodecID) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.CodecID = v
	})
}

func WithADPCM(v params.ADPCM) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.ADPCM = v
	})
}

func WithByteOrder(v binary.ByteOrder) DecoderConfigOption {
	return decoderConfigOptionFunc(func(c *DecoderConfig) {
		c.ByteOrder = v
	})
}
