// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	internal "github.com/godexture/format-flac/internal"
	optional "github.com/godexture/sdk/optional"
)

type DemuxerConfig struct {
	Strict optional.Optional[bool]
}

type DemuxerConfigOption func(*DemuxerConfig)

func NewDemuxerConfig(options ...DemuxerConfigOption) DemuxerConfig {
	var config DemuxerConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithStrict(v bool) DemuxerConfigOption {
	return func(c *DemuxerConfig) {
		c.Strict = optional.Some(v)
	}
}

func (c DemuxerConfig) ApplyDefaults() internal.DemuxerConfig {
	config := internal.DemuxerConfig{}
	config.Strict = c.Strict.ValueOr(config.Strict)
	return config
}
