// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	config "github.com/godexture/codec-flac/internal/config"
)

type DecoderConfig config.DecoderConfig

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config := DecoderConfig(config.DefaultDecoderConfig)
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithStrict(v bool) DecoderConfigOption {
	return func(c *DecoderConfig) {
		c.Strict = v
	}
}

func (c DecoderConfig) ResolveDefault() config.DecoderConfig {
	return config.DefaultDecoderConfig
}

func (c DecoderConfig) Resolve() config.DecoderConfig {
	return config.DecoderConfig(c)
}
