// Code generated by config-generator. DO NOT EDIT.

package filter

import (
	config "github.com/godexture/filter-audio/internal/config"
)

type ReverbConfig config.ReverbConfig

type ReverbConfigOption interface {
	applyReverbConfig(*ReverbConfig)
}

type reverbConfigOptionFunc func(*ReverbConfig)

func (f reverbConfigOptionFunc) applyReverbConfig(c *ReverbConfig) {
	f(c)
}

func NewReverbConfig(options ...ReverbConfigOption) ReverbConfig {
	config := ReverbConfig(config.DefaultReverbConfig)
	for _, option := range options {
		option.applyReverbConfig(&config)
	}
	return config
}

func (c ReverbConfig) ResolveDefault() config.ReverbConfig {
	return config.ReverbConfig(config.DefaultReverbConfig)
}

func (c ReverbConfig) Resolve() config.ReverbConfig {
	return config.ReverbConfig(c)
}

func (c ReverbConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c ReverbConfig) FieldChoices(field string) []string {
	switch field {
	default:
		return nil
	}
}

func WithRoomSize(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.RoomSize = v
	})
}

func WithDamping(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.Damping = v
	})
}

func WithWetLevel(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.WetLevel = v
	})
}

func WithDryLevel(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.DryLevel = v
	})
}
