// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	domain "github.com/godexture/codec-mp3/internal/domain"
)

type DecoderConfig struct {
}

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	var config DecoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func (c DecoderConfig) ApplyDefaults() domain.DecoderConfig {
	config := domain.DecoderConfig{}
	return config
}
