// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	internal "github.com/godexture/format-flac/internal"
)

type MuxerConfig struct {
}

type MuxerConfigOption func(*MuxerConfig)

func NewMuxerConfig(options ...MuxerConfigOption) MuxerConfig {
	var config MuxerConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func (c MuxerConfig) ApplyDefaults() internal.MuxerConfig {
	config := internal.MuxerConfig{}
	return config
}
