// Code generated by config-generator. DO NOT EDIT.

package pcm

import (
	internal "github.com/godexture/codec-pcm/internal"
	media "github.com/godexture/core/domain/media"
	params "github.com/godexture/format-wav/params"
)

type EncoderConfig internal.EncoderConfig

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	config := EncoderConfig(internal.DefaultEncoderConfig)
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithCodecID(v media.CodecID) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.CodecID = v
	}
}

func WithADPCM(v params.ADPCM) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.ADPCM = v
	}
}

func (c EncoderConfig) ResolveDefault() internal.EncoderConfig {
	return internal.DefaultEncoderConfig
}

func (c EncoderConfig) Resolve() internal.EncoderConfig {
	return internal.EncoderConfig(c)
}
