// Code generated by config-generator. DO NOT EDIT.

package pcm

import (
	internal "github.com/godexture/codec-pcm/internal"
)

type DecoderConfig struct {
}

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	var config DecoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func (c DecoderConfig) ApplyDefaults() internal.DecoderConfig {
	config := internal.DefaultDecoderConfig
	return config
}
