package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/godexture/tools/internal/cli"
	"github.com/godexture/tools/internal/config-generator/types"
)

// Generate orchestrates the config generation process.
func Generate(output, packageName string, targets []*types.Target) {
	absOutput, _ := filepath.Abs(output)
	if absOutput == "" {
		absOutput = output
	}
	log.Printf("generating %s...", absOutput)
	defer log.Printf("generated %s", absOutput)

	usedImports := collectImports(targets)
	fieldsMap, fieldOrder := collectFields(targets)

	var body bytes.Buffer

	// Generate target boilerplate
	generateTargetStructs(&body, targets, packageName)

	// Generate field options
	generateFieldOptions(&body, fieldOrder, fieldsMap)

	// Handle Presets
	generatePresetOptions(&body, targets)

	// Assemble final source code
	var sourceCode bytes.Buffer
	sourceCode.WriteString("// Code generated by config-generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&sourceCode, "package %s\n", packageName)

	// filter imports used in the generated file
	finalImports := make(map[string]string)
	
	for _, name := range []string{"fmt", "math"} {
		if _, ok := usedImports[name]; !ok {
			usedImports[name] = name
		}
	}

	bodyStr := body.String()
	for name, path := range usedImports {
		if strings.Contains(bodyStr, name+".") {
			finalImports[name] = path
		}
	}

	if len(finalImports) > 0 {
		names := make([]string, 0, len(finalImports))
		for name := range finalImports {
			names = append(names, name)
		}
		sort.Strings(names)
		sourceCode.WriteString("\nimport (\n")
		for _, name := range names {
			fmt.Fprintf(&sourceCode, "\t%s \"%s\"\n", name, finalImports[name])
		}
		sourceCode.WriteString(")\n")
	}
	sourceCode.WriteString("\n")
	sourceCode.WriteString(body.String())

	formatted, err := format.Source(sourceCode.Bytes())
	if err != nil {
		fmt.Println(sourceCode.String())
		cli.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(output, formatted, 0644); err != nil {
		cli.Fatalf("write %s: %v", output, err)
	}
}
