// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	internal "github.com/godexture/godec/plugin/mp3/internal/format"
)

type DemuxerConfig internal.DemuxerConfig

type DemuxerConfigOption interface {
	applyDemuxerConfig(*DemuxerConfig)
}

type demuxerConfigOptionFunc func(*DemuxerConfig)

func (f demuxerConfigOptionFunc) applyDemuxerConfig(c *DemuxerConfig) {
	f(c)
}

func NewDemuxerConfig(options ...DemuxerConfigOption) (DemuxerConfig, error) {
	config := DemuxerConfig(DemuxerConfig{})
	for _, option := range options {
		option.applyDemuxerConfig(&config)
	}
	if err := config.Validate(); err != nil {
		return config, err
	}
	return config, nil
}

func MustNewDemuxerConfig(options ...DemuxerConfigOption) DemuxerConfig {
	config, err := NewDemuxerConfig(options...)
	if err != nil {
		panic(err)
	}
	return config
}

func (c DemuxerConfig) ResolveDefault() internal.DemuxerConfig {
	return internal.DemuxerConfig(DemuxerConfig{})
}

func (c DemuxerConfig) Resolve() internal.DemuxerConfig {
	return internal.DemuxerConfig(c)
}

func (c DemuxerConfig) Validate() error {
	return nil
}

type MuxerConfig internal.MuxerConfig

type MuxerConfigOption interface {
	applyMuxerConfig(*MuxerConfig)
}

type muxerConfigOptionFunc func(*MuxerConfig)

func (f muxerConfigOptionFunc) applyMuxerConfig(c *MuxerConfig) {
	f(c)
}

func NewMuxerConfig(options ...MuxerConfigOption) (MuxerConfig, error) {
	config := MuxerConfig(MuxerConfig{})
	for _, option := range options {
		option.applyMuxerConfig(&config)
	}
	if err := config.Validate(); err != nil {
		return config, err
	}
	return config, nil
}

func MustNewMuxerConfig(options ...MuxerConfigOption) MuxerConfig {
	config, err := NewMuxerConfig(options...)
	if err != nil {
		panic(err)
	}
	return config
}

func (c MuxerConfig) ResolveDefault() internal.MuxerConfig {
	return internal.MuxerConfig(MuxerConfig{})
}

func (c MuxerConfig) Resolve() internal.MuxerConfig {
	return internal.MuxerConfig(c)
}

func (c MuxerConfig) Validate() error {
	return nil
}
