package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
)

// Table represents a static table definition to be generated.
type Table struct {
	Name   string
	Type   string
	Data   any
	Format string // If empty, "%v" is used
}

// Generate generates a Go source file containing the provided tables.
func Generate(filename string, pkgName string, tables []Table) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, t := range tables {
		fmt.Fprintf(&buf, "var %s = %s{\n", t.Name, t.Type)
		formatData(&buf, reflect.ValueOf(t.Data), 1, t.Format)
		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format error: %w", err)
	}

	if err := os.WriteFile(filename, formatted, 0644); err != nil {
		return fmt.Errorf("write error: %w", err)
	}

	return nil
}

func formatData(buf *bytes.Buffer, v reflect.Value, depth int, formatStr string) {
	indent := bytes.Repeat([]byte("\t"), depth)

	if formatStr == "" {
		formatStr = "%v"
	}

	switch v.Kind() {
	case reflect.Slice, reflect.Array:
		for i := 0; i < v.Len(); i++ {
			elem := v.Index(i)
			if elem.Kind() == reflect.Slice || elem.Kind() == reflect.Array {
				buf.Write(indent)
				buf.WriteString("{\n")
				formatData(buf, elem, depth+1, formatStr)
				buf.Write(indent)
				buf.WriteString("},")
				if i != v.Len()-1 {
					buf.WriteString("\n")
				}
			} else {
				if i == 0 || (i)%16 == 0 {
					buf.Write(indent)
				}
				fmt.Fprintf(buf, formatStr, getPrimitiveValue(elem))
				buf.WriteString(", ")
				if (i+1)%16 == 0 && i != v.Len()-1 {
					buf.WriteString("\n")
				}
			}
		}
		buf.WriteString("\n")
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			field := v.Type().Field(i)
			elem := v.Field(i)
			buf.Write(indent)
			fmt.Fprintf(buf, "%s: ", field.Name)
			if elem.Kind() == reflect.Slice || elem.Kind() == reflect.Array {
				fmt.Fprintf(buf, "%s{\n", field.Type.String())
				formatData(buf, elem, depth+1, formatStr)
				buf.Write(indent)
				buf.WriteString("},\n")
			} else {
				fmt.Fprintf(buf, formatStr, getPrimitiveValue(elem))
				buf.WriteString(",\n")
			}
		}
	}
}

func getPrimitiveValue(v reflect.Value) any {
	switch v.Kind() {
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return v.Uint()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int()
	case reflect.Float32, reflect.Float64:
		return v.Float()
	case reflect.String:
		return v.String()
	case reflect.Bool:
		return v.Bool()
	default:
		if v.CanInterface() {
			return v.Interface()
		}
		return fmt.Sprintf("%v", v)
	}
}
