//go:build js && wasm

// Code generated by gowasm-bindgen. DO NOT EDIT.

package main

import (
	"fmt"
	"syscall/js"
)

const ErrorFieldName = "__error"

func recoverFunc(fn func(js.Value, []js.Value) interface{}) js.Func {
	return js.FuncOf(func(this js.Value, args []js.Value) (ret interface{}) {
		defer func() {
			if r := recover(); r != nil {
				ret = map[string]interface{}{ErrorFieldName: fmt.Sprintf("panic: %v", r)}
			}
		}()
		return fn(this, args)
	})
}

func init() {
	js.Global().Set("catalog", recoverFunc(wasmCatalog))
	js.Global().Set("resolve", recoverFunc(wasmResolve))
	js.Global().Set("start", recoverFunc(wasmStart))
	js.Global().Set("snapshot", recoverFunc(wasmSnapshot))
	js.Global().Set("cancel", recoverFunc(wasmCancel))
	js.Global().Set("result", recoverFunc(wasmResult))
}

func wasmCatalog(_ js.Value, args []js.Value) interface{} {
	result, err := Catalog()
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return result
}

func wasmResolve(_ js.Value, args []js.Value) interface{} {
	input := func() []byte {
		length := args[0].Length()
		result := make([]byte, length)
		js.CopyBytesToGo(result, args[0])
		return result
	}()
	specJSON := args[1].String()
	result, err := Resolve(input, specJSON)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return result
}

func wasmStart(_ js.Value, args []js.Value) interface{} {
	input := func() []byte {
		length := args[0].Length()
		result := make([]byte, length)
		js.CopyBytesToGo(result, args[0])
		return result
	}()
	specJSON := args[1].String()
	result, err := Start(input, specJSON)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return result
}

func wasmSnapshot(_ js.Value, args []js.Value) interface{} {
	jobID := args[0].String()
	result, err := Snapshot(jobID)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return result
}

func wasmCancel(_ js.Value, args []js.Value) interface{} {
	jobID := args[0].String()
	err := Cancel(jobID)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return nil
}

func wasmResult(_ js.Value, args []js.Value) interface{} {
	jobID := args[0].String()
	result, err := Result(jobID)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return func() js.Value {
		arr := js.Global().Get("Uint8Array").New(len(result))
		js.CopyBytesToJS(arr, result)
		return arr
	}()
}

