// Code generated by config-generator. DO NOT EDIT.

package filter

import (
	media "github.com/godexture/core/domain/media"
	config "github.com/godexture/filter-audio/internal/config"
	time "time"
)

type FormatConfig config.FormatConfig

type FormatConfigOption interface {
	applyFormatConfig(*FormatConfig)
}

type formatConfigOptionFunc func(*FormatConfig)

func (f formatConfigOptionFunc) applyFormatConfig(c *FormatConfig) {
	f(c)
}

func NewFormatConfig(options ...FormatConfigOption) FormatConfig {
	config := FormatConfig(config.DefaultFormatConfig)
	for _, option := range options {
		option.applyFormatConfig(&config)
	}
	return config
}

func (c FormatConfig) ResolveDefault() config.FormatConfig {
	return config.FormatConfig(config.DefaultFormatConfig)
}

func (c FormatConfig) Resolve() config.FormatConfig {
	return config.FormatConfig(c)
}

func (c FormatConfig) Validate() error {
	return c.Resolve().Validate()
}

type ResampleConfig config.ResampleConfig

type ResampleConfigOption interface {
	applyResampleConfig(*ResampleConfig)
}

type resampleConfigOptionFunc func(*ResampleConfig)

func (f resampleConfigOptionFunc) applyResampleConfig(c *ResampleConfig) {
	f(c)
}

func NewResampleConfig(options ...ResampleConfigOption) ResampleConfig {
	config := ResampleConfig(config.DefaultResampleConfig)
	for _, option := range options {
		option.applyResampleConfig(&config)
	}
	return config
}

func (c ResampleConfig) ResolveDefault() config.ResampleConfig {
	return config.ResampleConfig(config.DefaultResampleConfig)
}

func (c ResampleConfig) Resolve() config.ResampleConfig {
	return config.ResampleConfig(c)
}

func (c ResampleConfig) Validate() error {
	return c.Resolve().Validate()
}

type RemixConfig config.RemixConfig

type RemixConfigOption interface {
	applyRemixConfig(*RemixConfig)
}

type remixConfigOptionFunc func(*RemixConfig)

func (f remixConfigOptionFunc) applyRemixConfig(c *RemixConfig) {
	f(c)
}

func NewRemixConfig(options ...RemixConfigOption) RemixConfig {
	config := RemixConfig(config.DefaultRemixConfig)
	for _, option := range options {
		option.applyRemixConfig(&config)
	}
	return config
}

func (c RemixConfig) ResolveDefault() config.RemixConfig {
	return config.RemixConfig(config.DefaultRemixConfig)
}

func (c RemixConfig) Resolve() config.RemixConfig {
	return config.RemixConfig(c)
}

func (c RemixConfig) Validate() error {
	return c.Resolve().Validate()
}

type GainConfig config.GainConfig

type GainConfigOption interface {
	applyGainConfig(*GainConfig)
}

type gainConfigOptionFunc func(*GainConfig)

func (f gainConfigOptionFunc) applyGainConfig(c *GainConfig) {
	f(c)
}

func NewGainConfig(options ...GainConfigOption) GainConfig {
	config := GainConfig(config.DefaultGainConfig)
	for _, option := range options {
		option.applyGainConfig(&config)
	}
	return config
}

func (c GainConfig) ResolveDefault() config.GainConfig {
	return config.GainConfig(config.DefaultGainConfig)
}

func (c GainConfig) Resolve() config.GainConfig {
	return config.GainConfig(c)
}

func (c GainConfig) Validate() error {
	return c.Resolve().Validate()
}

type NormalizeConfig config.NormalizeConfig

type NormalizeConfigOption interface {
	applyNormalizeConfig(*NormalizeConfig)
}

type normalizeConfigOptionFunc func(*NormalizeConfig)

func (f normalizeConfigOptionFunc) applyNormalizeConfig(c *NormalizeConfig) {
	f(c)
}

func NewNormalizeConfig(options ...NormalizeConfigOption) NormalizeConfig {
	config := NormalizeConfig(config.DefaultNormalizeConfig)
	for _, option := range options {
		option.applyNormalizeConfig(&config)
	}
	return config
}

func (c NormalizeConfig) ResolveDefault() config.NormalizeConfig {
	return config.NormalizeConfig(config.DefaultNormalizeConfig)
}

func (c NormalizeConfig) Resolve() config.NormalizeConfig {
	return config.NormalizeConfig(c)
}

func (c NormalizeConfig) Validate() error {
	return c.Resolve().Validate()
}

type FadeConfig config.FadeConfig

type FadeConfigOption interface {
	applyFadeConfig(*FadeConfig)
}

type fadeConfigOptionFunc func(*FadeConfig)

func (f fadeConfigOptionFunc) applyFadeConfig(c *FadeConfig) {
	f(c)
}

func NewFadeConfig(options ...FadeConfigOption) FadeConfig {
	config := FadeConfig(config.DefaultFadeConfig)
	for _, option := range options {
		option.applyFadeConfig(&config)
	}
	return config
}

func (c FadeConfig) ResolveDefault() config.FadeConfig {
	return config.FadeConfig(config.DefaultFadeConfig)
}

func (c FadeConfig) Resolve() config.FadeConfig {
	return config.FadeConfig(c)
}

func (c FadeConfig) Validate() error {
	return c.Resolve().Validate()
}

type DCOffsetConfig config.DCOffsetConfig

type DCOffsetConfigOption interface {
	applyDCOffsetConfig(*DCOffsetConfig)
}

type dCOffsetConfigOptionFunc func(*DCOffsetConfig)

func (f dCOffsetConfigOptionFunc) applyDCOffsetConfig(c *DCOffsetConfig) {
	f(c)
}

func NewDCOffsetConfig(options ...DCOffsetConfigOption) DCOffsetConfig {
	config := DCOffsetConfig(config.DefaultDCOffsetConfig)
	for _, option := range options {
		option.applyDCOffsetConfig(&config)
	}
	return config
}

func (c DCOffsetConfig) ResolveDefault() config.DCOffsetConfig {
	return config.DCOffsetConfig(config.DefaultDCOffsetConfig)
}

func (c DCOffsetConfig) Resolve() config.DCOffsetConfig {
	return config.DCOffsetConfig(c)
}

func (c DCOffsetConfig) Validate() error {
	return c.Resolve().Validate()
}

type GateConfig config.GateConfig

type GateConfigOption interface {
	applyGateConfig(*GateConfig)
}

type gateConfigOptionFunc func(*GateConfig)

func (f gateConfigOptionFunc) applyGateConfig(c *GateConfig) {
	f(c)
}

func NewGateConfig(options ...GateConfigOption) GateConfig {
	config := GateConfig(config.DefaultGateConfig)
	for _, option := range options {
		option.applyGateConfig(&config)
	}
	return config
}

func (c GateConfig) ResolveDefault() config.GateConfig {
	return config.GateConfig(config.DefaultGateConfig)
}

func (c GateConfig) Resolve() config.GateConfig {
	return config.GateConfig(c)
}

func (c GateConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c GateConfig) FieldChoices(field string) []string {
	switch field {
	case "GateMode":
		return []string{"hard", "lowpass"}
	default:
		return nil
	}
}

type TrimConfig config.TrimConfig

type TrimConfigOption interface {
	applyTrimConfig(*TrimConfig)
}

type trimConfigOptionFunc func(*TrimConfig)

func (f trimConfigOptionFunc) applyTrimConfig(c *TrimConfig) {
	f(c)
}

func NewTrimConfig(options ...TrimConfigOption) TrimConfig {
	config := TrimConfig(config.DefaultTrimConfig)
	for _, option := range options {
		option.applyTrimConfig(&config)
	}
	return config
}

func (c TrimConfig) ResolveDefault() config.TrimConfig {
	return config.TrimConfig(config.DefaultTrimConfig)
}

func (c TrimConfig) Resolve() config.TrimConfig {
	return config.TrimConfig(c)
}

func (c TrimConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c TrimConfig) FieldChoices(field string) []string {
	switch field {
	case "TrimMode":
		return []string{"both", "start", "end"}
	default:
		return nil
	}
}

type SpeedConfig config.SpeedConfig

type SpeedConfigOption interface {
	applySpeedConfig(*SpeedConfig)
}

type speedConfigOptionFunc func(*SpeedConfig)

func (f speedConfigOptionFunc) applySpeedConfig(c *SpeedConfig) {
	f(c)
}

func NewSpeedConfig(options ...SpeedConfigOption) SpeedConfig {
	config := SpeedConfig(config.DefaultSpeedConfig)
	for _, option := range options {
		option.applySpeedConfig(&config)
	}
	return config
}

func (c SpeedConfig) ResolveDefault() config.SpeedConfig {
	return config.SpeedConfig(config.DefaultSpeedConfig)
}

func (c SpeedConfig) Resolve() config.SpeedConfig {
	return config.SpeedConfig(c)
}

func (c SpeedConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c SpeedConfig) FieldChoices(field string) []string {
	switch field {
	case "Mode":
		return []string{"interpolate", "relabel"}
	default:
		return nil
	}
}

type CompressorConfig config.CompressorConfig

type CompressorConfigOption interface {
	applyCompressorConfig(*CompressorConfig)
}

type compressorConfigOptionFunc func(*CompressorConfig)

func (f compressorConfigOptionFunc) applyCompressorConfig(c *CompressorConfig) {
	f(c)
}

func NewCompressorConfig(options ...CompressorConfigOption) CompressorConfig {
	config := CompressorConfig(config.DefaultCompressorConfig)
	for _, option := range options {
		option.applyCompressorConfig(&config)
	}
	return config
}

func (c CompressorConfig) ResolveDefault() config.CompressorConfig {
	return config.CompressorConfig(config.DefaultCompressorConfig)
}

func (c CompressorConfig) Resolve() config.CompressorConfig {
	return config.CompressorConfig(c)
}

func (c CompressorConfig) Validate() error {
	return c.Resolve().Validate()
}

type EQConfig config.EQConfig

type EQConfigOption interface {
	applyEQConfig(*EQConfig)
}

type eQConfigOptionFunc func(*EQConfig)

func (f eQConfigOptionFunc) applyEQConfig(c *EQConfig) {
	f(c)
}

func NewEQConfig(options ...EQConfigOption) EQConfig {
	config := EQConfig(config.DefaultEQConfig)
	for _, option := range options {
		option.applyEQConfig(&config)
	}
	return config
}

func (c EQConfig) ResolveDefault() config.EQConfig {
	return config.EQConfig(config.DefaultEQConfig)
}

func (c EQConfig) Resolve() config.EQConfig {
	return config.EQConfig(c)
}

func (c EQConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c EQConfig) FieldChoices(field string) []string {
	switch field {
	case "Type":
		return []string{"peaking", "lowshelf", "highshelf", "lowpass", "highpass"}
	default:
		return nil
	}
}

type DelayConfig config.DelayConfig

type DelayConfigOption interface {
	applyDelayConfig(*DelayConfig)
}

type delayConfigOptionFunc func(*DelayConfig)

func (f delayConfigOptionFunc) applyDelayConfig(c *DelayConfig) {
	f(c)
}

func NewDelayConfig(options ...DelayConfigOption) DelayConfig {
	config := DelayConfig(config.DefaultDelayConfig)
	for _, option := range options {
		option.applyDelayConfig(&config)
	}
	return config
}

func (c DelayConfig) ResolveDefault() config.DelayConfig {
	return config.DelayConfig(config.DefaultDelayConfig)
}

func (c DelayConfig) Resolve() config.DelayConfig {
	return config.DelayConfig(c)
}

func (c DelayConfig) Validate() error {
	return c.Resolve().Validate()
}

type ReverbConfig config.ReverbConfig

type ReverbConfigOption interface {
	applyReverbConfig(*ReverbConfig)
}

type reverbConfigOptionFunc func(*ReverbConfig)

func (f reverbConfigOptionFunc) applyReverbConfig(c *ReverbConfig) {
	f(c)
}

func NewReverbConfig(options ...ReverbConfigOption) ReverbConfig {
	config := ReverbConfig(config.DefaultReverbConfig)
	for _, option := range options {
		option.applyReverbConfig(&config)
	}
	return config
}

func (c ReverbConfig) ResolveDefault() config.ReverbConfig {
	return config.ReverbConfig(config.DefaultReverbConfig)
}

func (c ReverbConfig) Resolve() config.ReverbConfig {
	return config.ReverbConfig(c)
}

func (c ReverbConfig) Validate() error {
	return c.Resolve().Validate()
}

type ConvolutionConfig config.ConvolutionConfig

type ConvolutionConfigOption interface {
	applyConvolutionConfig(*ConvolutionConfig)
}

type convolutionConfigOptionFunc func(*ConvolutionConfig)

func (f convolutionConfigOptionFunc) applyConvolutionConfig(c *ConvolutionConfig) {
	f(c)
}

func NewConvolutionConfig(options ...ConvolutionConfigOption) ConvolutionConfig {
	config := ConvolutionConfig(config.DefaultConvolutionConfig)
	for _, option := range options {
		option.applyConvolutionConfig(&config)
	}
	return config
}

func (c ConvolutionConfig) ResolveDefault() config.ConvolutionConfig {
	return config.ConvolutionConfig(config.DefaultConvolutionConfig)
}

func (c ConvolutionConfig) Resolve() config.ConvolutionConfig {
	return config.ConvolutionConfig(c)
}

func (c ConvolutionConfig) Validate() error {
	return c.Resolve().Validate()
}

type MixerConfig config.MixerConfig

type MixerConfigOption interface {
	applyMixerConfig(*MixerConfig)
}

type mixerConfigOptionFunc func(*MixerConfig)

func (f mixerConfigOptionFunc) applyMixerConfig(c *MixerConfig) {
	f(c)
}

func NewMixerConfig(options ...MixerConfigOption) MixerConfig {
	config := MixerConfig(config.DefaultMixerConfig)
	for _, option := range options {
		option.applyMixerConfig(&config)
	}
	return config
}

func (c MixerConfig) ResolveDefault() config.MixerConfig {
	return config.MixerConfig(config.DefaultMixerConfig)
}

func (c MixerConfig) Resolve() config.MixerConfig {
	return config.MixerConfig(c)
}

func (c MixerConfig) Validate() error {
	return c.Resolve().Validate()
}

type GateMode = config.GateMode

const (
	GateModeHard    = config.GateModeHard
	GateModeLowpass = config.GateModeLowpass
)

type TrimMode = config.TrimMode

const (
	TrimModeBoth  = config.TrimModeBoth
	TrimModeStart = config.TrimModeStart
	TrimModeEnd   = config.TrimModeEnd
)

type SpeedMode = config.SpeedMode

const (
	SpeedModeInterpolate = config.SpeedModeInterpolate
	SpeedModeRelabel     = config.SpeedModeRelabel
)

type EQType = config.EQType

const (
	EQTypePeaking   = config.EQTypePeaking
	EQTypeLowShelf  = config.EQTypeLowShelf
	EQTypeHighShelf = config.EQTypeHighShelf
	EQTypeLowPass   = config.EQTypeLowPass
	EQTypeHighPass  = config.EQTypeHighPass
)

func WithFormat(v media.SampleFormat) FormatConfigOption {
	return formatConfigOptionFunc(func(c *FormatConfig) {
		c.Format = v
	})
}

func WithBitsPerSample(v int) FormatConfigOption {
	return formatConfigOptionFunc(func(c *FormatConfig) {
		c.BitsPerSample = v
	})
}

func WithSampleRate(v int) ResampleConfigOption {
	return resampleConfigOptionFunc(func(c *ResampleConfig) {
		c.SampleRate = v
	})
}

func WithLayout(v media.ChannelLayout) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.Layout = v
	})
}

func WithCenterMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.CenterMixDB = v
	})
}

func WithSurroundMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.SurroundMixDB = v
	})
}

func WithLFEMixDB(v float64) RemixConfigOption {
	return remixConfigOptionFunc(func(c *RemixConfig) {
		c.LFEMixDB = v
	})
}

type NormalizeOption interface {
	RemixConfigOption
	ConvolutionConfigOption
	MixerConfigOption
}

type normalizeOpt struct{ v bool }

func (o normalizeOpt) applyRemixConfig(c *RemixConfig) {
	c.Normalize = o.v
}
func (o normalizeOpt) applyConvolutionConfig(c *ConvolutionConfig) {
	c.Normalize = o.v
}
func (o normalizeOpt) applyMixerConfig(c *MixerConfig) {
	c.Normalize = o.v
}

func WithNormalize(v bool) NormalizeOption {
	return normalizeOpt{v}
}

func WithDecibels(v float64) GainConfigOption {
	return gainConfigOptionFunc(func(c *GainConfig) {
		c.Decibels = v
	})
}

func WithTargetPeakDBFS(v float64) NormalizeConfigOption {
	return normalizeConfigOptionFunc(func(c *NormalizeConfig) {
		c.TargetPeakDBFS = v
	})
}

func WithAllowAmplification(v bool) NormalizeConfigOption {
	return normalizeConfigOptionFunc(func(c *NormalizeConfig) {
		c.AllowAmplification = v
	})
}

type MemoryLimitBytesOption interface {
	NormalizeConfigOption
	FadeConfigOption
	TrimConfigOption
}

type memoryLimitBytesOpt struct{ v int64 }

func (o memoryLimitBytesOpt) applyNormalizeConfig(c *NormalizeConfig) {
	c.MemoryLimitBytes = o.v
}
func (o memoryLimitBytesOpt) applyFadeConfig(c *FadeConfig) {
	c.MemoryLimitBytes = o.v
}
func (o memoryLimitBytesOpt) applyTrimConfig(c *TrimConfig) {
	c.MemoryLimitBytes = o.v
}

func WithMemoryLimitBytes(v int64) MemoryLimitBytesOption {
	return memoryLimitBytesOpt{v}
}

type TempDirOption interface {
	NormalizeConfigOption
	FadeConfigOption
	TrimConfigOption
}

type tempDirOpt struct{ v string }

func (o tempDirOpt) applyNormalizeConfig(c *NormalizeConfig) {
	c.TempDir = o.v
}
func (o tempDirOpt) applyFadeConfig(c *FadeConfig) {
	c.TempDir = o.v
}
func (o tempDirOpt) applyTrimConfig(c *TrimConfig) {
	c.TempDir = o.v
}

func WithTempDir(v string) TempDirOption {
	return tempDirOpt{v}
}

func WithFadeIn(v time.Duration) FadeConfigOption {
	return fadeConfigOptionFunc(func(c *FadeConfig) {
		c.FadeIn = v
	})
}

func WithFadeOut(v time.Duration) FadeConfigOption {
	return fadeConfigOptionFunc(func(c *FadeConfig) {
		c.FadeOut = v
	})
}

func WithPole(v float64) DCOffsetConfigOption {
	return dCOffsetConfigOptionFunc(func(c *DCOffsetConfig) {
		c.Pole = v
	})
}

type ThresholdDBFSOption interface {
	GateConfigOption
	TrimConfigOption
	CompressorConfigOption
}

type thresholdDBFSOpt struct{ v float64 }

func (o thresholdDBFSOpt) applyGateConfig(c *GateConfig) {
	c.ThresholdDBFS = o.v
}
func (o thresholdDBFSOpt) applyTrimConfig(c *TrimConfig) {
	c.ThresholdDBFS = o.v
}
func (o thresholdDBFSOpt) applyCompressorConfig(c *CompressorConfig) {
	c.ThresholdDBFS = o.v
}

func WithThresholdDBFS(v float64) ThresholdDBFSOption {
	return thresholdDBFSOpt{v}
}

func WithGateMode(v GateMode) GateConfigOption {
	return gateConfigOptionFunc(func(c *GateConfig) {
		c.GateMode = v
	})
}

func WithRangeDB(v float64) GateConfigOption {
	return gateConfigOptionFunc(func(c *GateConfig) {
		c.RangeDB = v
	})
}

type AttackMsOption interface {
	GateConfigOption
	CompressorConfigOption
}

type attackMsOpt struct{ v float64 }

func (o attackMsOpt) applyGateConfig(c *GateConfig) {
	c.AttackMs = o.v
}
func (o attackMsOpt) applyCompressorConfig(c *CompressorConfig) {
	c.AttackMs = o.v
}

func WithAttackMs(v float64) AttackMsOption {
	return attackMsOpt{v}
}

type ReleaseMsOption interface {
	GateConfigOption
	CompressorConfigOption
}

type releaseMsOpt struct{ v float64 }

func (o releaseMsOpt) applyGateConfig(c *GateConfig) {
	c.ReleaseMs = o.v
}
func (o releaseMsOpt) applyCompressorConfig(c *CompressorConfig) {
	c.ReleaseMs = o.v
}

func WithReleaseMs(v float64) ReleaseMsOption {
	return releaseMsOpt{v}
}

func WithOpenFrequencyHz(v float64) GateConfigOption {
	return gateConfigOptionFunc(func(c *GateConfig) {
		c.OpenFrequencyHz = v
	})
}

func WithCloseFrequencyHz(v float64) GateConfigOption {
	return gateConfigOptionFunc(func(c *GateConfig) {
		c.CloseFrequencyHz = v
	})
}

func WithTrimMode(v TrimMode) TrimConfigOption {
	return trimConfigOptionFunc(func(c *TrimConfig) {
		c.TrimMode = v
	})
}

func WithApproximateSilence(v bool) TrimConfigOption {
	return trimConfigOptionFunc(func(c *TrimConfig) {
		c.ApproximateSilence = v
	})
}

func WithFactor(v float64) SpeedConfigOption {
	return speedConfigOptionFunc(func(c *SpeedConfig) {
		c.Factor = v
	})
}

func WithMode(v SpeedMode) SpeedConfigOption {
	return speedConfigOptionFunc(func(c *SpeedConfig) {
		c.Mode = v
	})
}

func WithRatio(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.Ratio = v
	})
}

func WithKneeDB(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.KneeDB = v
	})
}

func WithMakeupGainDB(v float64) CompressorConfigOption {
	return compressorConfigOptionFunc(func(c *CompressorConfig) {
		c.MakeupGainDB = v
	})
}

func WithType(v EQType) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.Type = v
	})
}

func WithFrequencyHz(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.FrequencyHz = v
	})
}

func WithGainDB(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.GainDB = v
	})
}

func WithQ(v float64) EQConfigOption {
	return eQConfigOptionFunc(func(c *EQConfig) {
		c.Q = v
	})
}

func WithDelayMs(v float64) DelayConfigOption {
	return delayConfigOptionFunc(func(c *DelayConfig) {
		c.DelayMs = v
	})
}

func WithFeedback(v float64) DelayConfigOption {
	return delayConfigOptionFunc(func(c *DelayConfig) {
		c.Feedback = v
	})
}

type WetLevelOption interface {
	DelayConfigOption
	ReverbConfigOption
}

type wetLevelOpt struct{ v float64 }

func (o wetLevelOpt) applyDelayConfig(c *DelayConfig) {
	c.WetLevel = o.v
}
func (o wetLevelOpt) applyReverbConfig(c *ReverbConfig) {
	c.WetLevel = o.v
}

func WithWetLevel(v float64) WetLevelOption {
	return wetLevelOpt{v}
}

type DryLevelOption interface {
	DelayConfigOption
	ReverbConfigOption
}

type dryLevelOpt struct{ v float64 }

func (o dryLevelOpt) applyDelayConfig(c *DelayConfig) {
	c.DryLevel = o.v
}
func (o dryLevelOpt) applyReverbConfig(c *ReverbConfig) {
	c.DryLevel = o.v
}

func WithDryLevel(v float64) DryLevelOption {
	return dryLevelOpt{v}
}

func WithRoomSize(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.RoomSize = v
	})
}

func WithDamping(v float64) ReverbConfigOption {
	return reverbConfigOptionFunc(func(c *ReverbConfig) {
		c.Damping = v
	})
}

func WithImpulseResponse(v [][]float32) ConvolutionConfigOption {
	return convolutionConfigOptionFunc(func(c *ConvolutionConfig) {
		c.ImpulseResponse = v
	})
}

func WithImpulseRate(v int) ConvolutionConfigOption {
	return convolutionConfigOptionFunc(func(c *ConvolutionConfig) {
		c.ImpulseRate = v
	})
}

func WithWetDryMix(v float64) ConvolutionConfigOption {
	return convolutionConfigOptionFunc(func(c *ConvolutionConfig) {
		c.WetDryMix = v
	})
}

func WithBlockSize(v int) ConvolutionConfigOption {
	return convolutionConfigOptionFunc(func(c *ConvolutionConfig) {
		c.BlockSize = v
	})
}

func WithWeights(v [][]float64) MixerConfigOption {
	return mixerConfigOptionFunc(func(c *MixerConfig) {
		c.Weights = v
	})
}
