// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	config "github.com/godexture/codec-flac/internal/config"
	flac "github.com/godexture/codec-flac/internal/flac"
)

type EncoderConfig config.EncoderConfig

type EncoderConfigOption interface {
	applyEncoderConfig(*EncoderConfig)
}

type encoderConfigOptionFunc func(*EncoderConfig)

func (f encoderConfigOptionFunc) applyEncoderConfig(c *EncoderConfig) {
	f(c)
}

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	config := EncoderConfig(config.DefaultEncoderConfig)
	for _, option := range options {
		option.applyEncoderConfig(&config)
	}
	return config
}

func (c EncoderConfig) ResolveDefault() config.EncoderConfig {
	return config.EncoderConfig(config.DefaultEncoderConfig)
}

func (c EncoderConfig) Resolve() config.EncoderConfig {
	return config.EncoderConfig(c)
}

func (c EncoderConfig) Validate() error {
	return c.Resolve().Validate()
}

func (c EncoderConfig) FieldChoices(field string) []string {
	switch field {
	case "StereoMode":
		return []string{"independent", "adaptive", "exhaustive"}
	case "FixedOrderSearch":
		return []string{"estimated", "exhaustive"}
	case "LPCOrderSearch":
		return []string{"estimated", "exhaustive"}
	case "RiceCost":
		return []string{"estimated", "exact"}
	case "BlockSplitMode":
		return []string{"estimated", "exact"}
	default:
		return nil
	}
}

type DecoderConfig config.DecoderConfig

type DecoderConfigOption interface {
	applyDecoderConfig(*DecoderConfig)
}

type decoderConfigOptionFunc func(*DecoderConfig)

func (f decoderConfigOptionFunc) applyDecoderConfig(c *DecoderConfig) {
	f(c)
}

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config := DecoderConfig(config.DefaultDecoderConfig)
	for _, option := range options {
		option.applyDecoderConfig(&config)
	}
	return config
}

func (c DecoderConfig) ResolveDefault() config.DecoderConfig {
	return config.DecoderConfig(config.DefaultDecoderConfig)
}

func (c DecoderConfig) Resolve() config.DecoderConfig {
	return config.DecoderConfig(c)
}

type StereoMode = config.StereoMode

const (
	StereoIndependent = config.StereoIndependent
	StereoAdaptive    = config.StereoAdaptive
	StereoExhaustive  = config.StereoExhaustive
)

type OrderSearchMode = config.OrderSearchMode

const (
	OrderSearchEstimated  = config.OrderSearchEstimated
	OrderSearchExhaustive = config.OrderSearchExhaustive
)

type RiceCostMode = config.RiceCostMode

const (
	RiceCostEstimated = config.RiceCostEstimated
	RiceCostExact     = config.RiceCostExact
)

type BlockSplitMode = config.BlockSplitMode

const (
	BlockSplitEstimated = config.BlockSplitEstimated
	BlockSplitExact     = config.BlockSplitExact
)

func WithBlockSize(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.BlockSize = v
	})
}

func WithMaxFixedOrder(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.MaxFixedOrder = v
	})
}

func WithMaxLPCOrder(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.MaxLPCOrder = v
	})
}

func WithMaxRicePartitionOrder(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.MaxRicePartitionOrder = v
	})
}

func WithLPCPrecision(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.LPCPrecision = v
	})
}

func WithEnablePrecisionSearch(v bool) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.EnablePrecisionSearch = v
	})
}

func WithEnableWastedBits(v bool) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.EnableWastedBits = v
	})
}

func WithStereoMode(v StereoMode) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.StereoMode = v
	})
}

func WithFixedOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.FixedOrderSearch = v
	})
}

func WithLPCOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.LPCOrderSearch = v
	})
}

func WithRiceCost(v RiceCostMode) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.RiceCost = v
	})
}

func WithApodizations(v []flac.Apodization) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.Apodizations = v
	})
}

func WithBlockSplitDepth(v int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.BlockSplitDepth = v
	})
}

func WithBlockSplitMode(v BlockSplitMode) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.BlockSplitMode = v
	})
}

func WithStreamableSubset(v bool) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		c.StreamableSubset = v
	})
}

func WithStrict(v bool) DecoderConfigOption {
	return decoderConfigOptionFunc(func(c *DecoderConfig) {
		c.Strict = v
	})
}

func WithPreset(level int) EncoderConfigOption {
	return encoderConfigOptionFunc(func(c *EncoderConfig) {
		*c = EncoderConfig(config.GetPreset(level))
	})
}

func (c *EncoderConfig) ApplyPreset(level int) {
	*c = NewEncoderConfig(WithPreset(level))
}
