// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	flac "github.com/godexture/codec-flac/internal/flac"
)

type DecoderConfig struct {
}

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	var config DecoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func (c DecoderConfig) ApplyDefaults() flac.DecoderConfig {
	config := flac.DecoderConfig{}
	return config
}
