// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	flac "github.com/godexture/codec-flac/internal/flac"
	optional "github.com/godexture/sdk/optional"
)

type EncoderConfig struct {
	SampleRate            optional.Optional[int]
	Channels              optional.Optional[int]
	BitsPerSample         optional.Optional[int]
	BlockSize             optional.Optional[int]
	MaxFixedOrder         optional.Optional[int]
	MaxLPCOrder           optional.Optional[int]
	MaxRicePartitionOrder optional.Optional[int]
	LPCPrecision          optional.Optional[int]
	EnablePrecisionSearch optional.Optional[bool]
	EnableWastedBits      optional.Optional[bool]
	StereoMode            optional.Optional[StereoMode]
	FixedOrderSearch      optional.Optional[OrderSearchMode]
	LPCOrderSearch        optional.Optional[OrderSearchMode]
	RiceCost              optional.Optional[RiceCostMode]
	Apodizations          optional.Optional[[]Apodization]
	BlockSplitDepth       optional.Optional[int]
	BlockSplitMode        optional.Optional[BlockSplitMode]
	StreamableSubset      optional.Optional[bool]
	Workers               optional.Optional[int]
}

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	var config EncoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithSampleRate(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.SampleRate = optional.Some(v)
	}
}

func WithChannels(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Channels = optional.Some(v)
	}
}

func WithBitsPerSample(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BitsPerSample = optional.Some(v)
	}
}

func WithBlockSize(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSize = optional.Some(v)
	}
}

func WithMaxFixedOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxFixedOrder = optional.Some(v)
	}
}

func WithMaxLPCOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxLPCOrder = optional.Some(v)
	}
}

func WithMaxRicePartitionOrder(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.MaxRicePartitionOrder = optional.Some(v)
	}
}

func WithLPCPrecision(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.LPCPrecision = optional.Some(v)
	}
}

func WithEnablePrecisionSearch(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.EnablePrecisionSearch = optional.Some(v)
	}
}

func WithEnableWastedBits(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.EnableWastedBits = optional.Some(v)
	}
}

func WithStereoMode(v StereoMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.StereoMode = optional.Some(v)
	}
}

func WithFixedOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.FixedOrderSearch = optional.Some(v)
	}
}

func WithLPCOrderSearch(v OrderSearchMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.LPCOrderSearch = optional.Some(v)
	}
}

func WithRiceCost(v RiceCostMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.RiceCost = optional.Some(v)
	}
}

func WithApodizations(v []Apodization) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Apodizations = optional.Some(v)
	}
}

func WithBlockSplitDepth(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSplitDepth = optional.Some(v)
	}
}

func WithBlockSplitMode(v BlockSplitMode) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.BlockSplitMode = optional.Some(v)
	}
}

func WithStreamableSubset(v bool) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.StreamableSubset = optional.Some(v)
	}
}

func WithWorkers(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Workers = optional.Some(v)
	}
}

func (c EncoderConfig) ApplyDefaults() flac.EncoderConfig {
	config := flac.GetPreset(5)
	config.SampleRate = c.SampleRate.ValueOr(config.SampleRate)
	config.Channels = c.Channels.ValueOr(config.Channels)
	config.BitsPerSample = c.BitsPerSample.ValueOr(config.BitsPerSample)
	config.BlockSize = c.BlockSize.ValueOr(config.BlockSize)
	config.MaxFixedOrder = c.MaxFixedOrder.ValueOr(config.MaxFixedOrder)
	config.MaxLPCOrder = c.MaxLPCOrder.ValueOr(config.MaxLPCOrder)
	config.MaxRicePartitionOrder = c.MaxRicePartitionOrder.ValueOr(config.MaxRicePartitionOrder)
	config.LPCPrecision = c.LPCPrecision.ValueOr(config.LPCPrecision)
	config.EnablePrecisionSearch = c.EnablePrecisionSearch.ValueOr(config.EnablePrecisionSearch)
	config.EnableWastedBits = c.EnableWastedBits.ValueOr(config.EnableWastedBits)
	config.StereoMode = c.StereoMode.ValueOr(config.StereoMode)
	config.FixedOrderSearch = c.FixedOrderSearch.ValueOr(config.FixedOrderSearch)
	config.LPCOrderSearch = c.LPCOrderSearch.ValueOr(config.LPCOrderSearch)
	config.RiceCost = c.RiceCost.ValueOr(config.RiceCost)
	config.Apodizations = c.Apodizations.ValueOr(config.Apodizations)
	config.BlockSplitDepth = c.BlockSplitDepth.ValueOr(config.BlockSplitDepth)
	config.BlockSplitMode = c.BlockSplitMode.ValueOr(config.BlockSplitMode)
	config.StreamableSubset = c.StreamableSubset.ValueOr(config.StreamableSubset)
	config.Workers = c.Workers.ValueOr(config.Workers)
	return config
}

func PresetConfig(level int) EncoderConfig {
	preset := flac.GetPreset(normalizeCompressionLevel(level))
	return EncoderConfig{
		SampleRate:            optional.Some(preset.SampleRate),
		Channels:              optional.Some(preset.Channels),
		BitsPerSample:         optional.Some(preset.BitsPerSample),
		BlockSize:             optional.Some(preset.BlockSize),
		MaxFixedOrder:         optional.Some(preset.MaxFixedOrder),
		MaxLPCOrder:           optional.Some(preset.MaxLPCOrder),
		MaxRicePartitionOrder: optional.Some(preset.MaxRicePartitionOrder),
		LPCPrecision:          optional.Some(preset.LPCPrecision),
		EnablePrecisionSearch: optional.Some(preset.EnablePrecisionSearch),
		EnableWastedBits:      optional.Some(preset.EnableWastedBits),
		StereoMode:            optional.Some(preset.StereoMode),
		FixedOrderSearch:      optional.Some(preset.FixedOrderSearch),
		LPCOrderSearch:        optional.Some(preset.LPCOrderSearch),
		RiceCost:              optional.Some(preset.RiceCost),
		Apodizations:          optional.Some(preset.Apodizations),
		BlockSplitDepth:       optional.Some(preset.BlockSplitDepth),
		BlockSplitMode:        optional.Some(preset.BlockSplitMode),
		StreamableSubset:      optional.Some(preset.StreamableSubset),
		Workers:               optional.Some(preset.Workers),
	}
}

func WithPreset(level int) EncoderConfigOption {
	return func(c *EncoderConfig) { *c = PresetConfig(level) }
}
