// Code generated by config-generator. DO NOT EDIT.

package flac

import (
	flac "github.com/godexture/codec-flac/internal/flac"
	optional "github.com/godexture/sdk/optional"
)

type DecoderConfig struct {
	Strict optional.Optional[bool]
}

type DecoderConfigOption func(*DecoderConfig)

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	var config DecoderConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithStrict(v bool) DecoderConfigOption {
	return func(c *DecoderConfig) {
		c.Strict = optional.Some(v)
	}
}

func (c DecoderConfig) ApplyDefaults() flac.DecoderConfig {
	config := flac.DecoderConfig{}
	config.Strict = c.Strict.ValueOr(config.Strict)
	return config
}
