// Code generated by config-generator. DO NOT EDIT.

package wav

import (
	internal "github.com/godexture/format-wav/internal"
)

type DemuxerConfig internal.DemuxerConfig

type DemuxerConfigOption interface {
	applyDemuxerConfig(*DemuxerConfig)
}

type demuxerConfigOptionFunc func(*DemuxerConfig)

func (f demuxerConfigOptionFunc) applyDemuxerConfig(c *DemuxerConfig) {
	f(c)
}

func NewDemuxerConfig(options ...DemuxerConfigOption) DemuxerConfig {
	config := DemuxerConfig(DemuxerConfig{})
	for _, option := range options {
		option.applyDemuxerConfig(&config)
	}
	return config
}

func (c DemuxerConfig) ResolveDefault() internal.DemuxerConfig {
	return internal.DemuxerConfig(DemuxerConfig{})
}

func (c DemuxerConfig) Resolve() internal.DemuxerConfig {
	return internal.DemuxerConfig(c)
}

type MuxerConfig internal.MuxerConfig

type MuxerConfigOption interface {
	applyMuxerConfig(*MuxerConfig)
}

type muxerConfigOptionFunc func(*MuxerConfig)

func (f muxerConfigOptionFunc) applyMuxerConfig(c *MuxerConfig) {
	f(c)
}

func NewMuxerConfig(options ...MuxerConfigOption) MuxerConfig {
	config := MuxerConfig(MuxerConfig{})
	for _, option := range options {
		option.applyMuxerConfig(&config)
	}
	return config
}

func (c MuxerConfig) ResolveDefault() internal.MuxerConfig {
	return internal.MuxerConfig(MuxerConfig{})
}

func (c MuxerConfig) Resolve() internal.MuxerConfig {
	return internal.MuxerConfig(c)
}

func WithForceRF64(v bool) MuxerConfigOption {
	return muxerConfigOptionFunc(func(c *MuxerConfig) {
		c.ForceRF64 = v
	})
}
