// Code generated by config-generator. DO NOT EDIT.

package wav

import (
	internal "github.com/godexture/format-wav/internal"
	optional "github.com/godexture/sdk/optional"
)

type MuxerConfig struct {
	ForceRF64 optional.Optional[bool]
}

type MuxerConfigOption func(*MuxerConfig)

func NewMuxerConfig(options ...MuxerConfigOption) MuxerConfig {
	var config MuxerConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithForceRF64(v bool) MuxerConfigOption {
	return func(c *MuxerConfig) {
		c.ForceRF64 = optional.Some(v)
	}
}

func (c MuxerConfig) ApplyDefaults() internal.MuxerConfig {
	config := internal.MuxerConfig{}
	config.ForceRF64 = c.ForceRF64.ValueOr(config.ForceRF64)
	return config
}
