// Code generated by config-generator. DO NOT EDIT.

package wav

import (
	internal "github.com/godexture/format-wav/internal"
)

type MuxerConfig internal.MuxerConfig

type MuxerConfigOption func(*MuxerConfig)

func NewMuxerConfig(options ...MuxerConfigOption) MuxerConfig {
	config := MuxerConfig(internal.MuxerConfig{})
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithForceRF64(v bool) MuxerConfigOption {
	return func(c *MuxerConfig) {
		c.ForceRF64 = v
	}
}

func (c MuxerConfig) ResolveDefault() internal.MuxerConfig {
	return internal.MuxerConfig{}
}

func (c MuxerConfig) Resolve() internal.MuxerConfig {
	return internal.MuxerConfig(c)
}
