// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	internal "github.com/godexture/format-mp3/internal"
)

type DemuxerConfig struct {
}

type DemuxerConfigOption func(*DemuxerConfig)

func NewDemuxerConfig(options ...DemuxerConfigOption) DemuxerConfig {
	var config DemuxerConfig
	for _, option := range options {
		option(&config)
	}
	return config
}

func (c DemuxerConfig) ApplyDefaults() internal.DemuxerConfig {
	config := internal.DemuxerConfig{}
	return config
}
