// Code generated by enum-generator. DO NOT EDIT.

package config

func (v TrimMode) Valid() bool {
	switch v {
	case "both", "start", "end":
		return true
	}
	return false
}

func (v SpeedMode) Valid() bool {
	switch v {
	case "interpolate", "relabel":
		return true
	}
	return false
}
