// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	domain "github.com/godexture/codec-mp3/internal/domain"
)

type DecoderConfig domain.DecoderConfig

type DecoderConfigOption interface {
	applyDecoderConfig(*DecoderConfig)
}

type decoderConfigOptionFunc func(*DecoderConfig)

func (f decoderConfigOptionFunc) applyDecoderConfig(c *DecoderConfig) {
	f(c)
}

func NewDecoderConfig(options ...DecoderConfigOption) (DecoderConfig, error) {
	config := DecoderConfig(domain.DefaultDecoderConfig)
	for _, option := range options {
		option.applyDecoderConfig(&config)
	}
	if err := config.Validate(); err != nil {
		return config, err
	}
	return config, nil
}

func MustNewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config, err := NewDecoderConfig(options...)
	if err != nil {
		panic(err)
	}
	return config
}

func (c DecoderConfig) ResolveDefault() domain.DecoderConfig {
	return domain.DecoderConfig(domain.DefaultDecoderConfig)
}

func (c DecoderConfig) Resolve() domain.DecoderConfig {
	return domain.DecoderConfig(c)
}

func (c DecoderConfig) Validate() error {
	return nil
}
