// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	domain "github.com/godexture/codec-mp3/internal/domain"
)

type EncoderConfig domain.EncoderConfig

type EncoderConfigOption func(*EncoderConfig)

func NewEncoderConfig(options ...EncoderConfigOption) EncoderConfig {
	config := EncoderConfig(domain.DefaultEncoderConfig)
	for _, option := range options {
		option(&config)
	}
	return config
}

func WithBitrate(v int) EncoderConfigOption {
	return func(c *EncoderConfig) {
		c.Bitrate = v
	}
}

func (c EncoderConfig) ResolveDefault() domain.EncoderConfig {
	return domain.DefaultEncoderConfig
}

func (c EncoderConfig) Resolve() domain.EncoderConfig {
	return domain.EncoderConfig(c)
}
