// Code generated by config-generator. DO NOT EDIT.

package mp3

import (
	domain "github.com/godexture/codec-mp3/internal/domain"
)

type DecoderConfig domain.DecoderConfig

type DecoderConfigOption interface {
	applyDecoderConfig(*DecoderConfig)
}

type decoderConfigOptionFunc func(*DecoderConfig)

func (f decoderConfigOptionFunc) applyDecoderConfig(c *DecoderConfig) {
	f(c)
}

func NewDecoderConfig(options ...DecoderConfigOption) DecoderConfig {
	config := DecoderConfig(domain.DefaultDecoderConfig)
	for _, option := range options {
		option.applyDecoderConfig(&config)
	}
	return config
}

func (c DecoderConfig) ResolveDefault() domain.DecoderConfig {
	return domain.DecoderConfig(domain.DefaultDecoderConfig)
}

func (c DecoderConfig) Resolve() domain.DecoderConfig {
	return domain.DecoderConfig(c)
}
