//go:build js && wasm

// Code generated by gowasm-bindgen. DO NOT EDIT.

package main

import (
	"fmt"
	"syscall/js"
)

const ErrorFieldName = "__error"

func recoverFunc(fn func(js.Value, []js.Value) interface{}) js.Func {
	return js.FuncOf(func(this js.Value, args []js.Value) (ret interface{}) {
		defer func() {
			if r := recover(); r != nil {
				ret = map[string]interface{}{ErrorFieldName: fmt.Sprintf("panic: %v", r)}
			}
		}()
		return fn(this, args)
	})
}

func init() {
	js.Global().Set("hello", recoverFunc(wasmHello))
}

func wasmHello(_ js.Value, args []js.Value) interface{} {
	result := Hello()
	return result
}

