//go:build js && wasm

// Code generated by gowasm-bindgen. DO NOT EDIT.

package main

import (
	"fmt"
	"syscall/js"
)

const ErrorFieldName = "__error"

func recoverFunc(fn func(js.Value, []js.Value) interface{}) js.Func {
	return js.FuncOf(func(this js.Value, args []js.Value) (ret interface{}) {
		defer func() {
			if r := recover(); r != nil {
				ret = map[string]interface{}{ErrorFieldName: fmt.Sprintf("panic: %v", r)}
			}
		}()
		return fn(this, args)
	})
}

func init() {
	js.Global().Set("convert", recoverFunc(wasmConvert))
}

func wasmConvert(_ js.Value, args []js.Value) interface{} {
	input := func() []byte {
		length := args[0].Length()
		result := make([]byte, length)
		js.CopyBytesToGo(result, args[0])
		return result
	}()
	format := args[1].String()
	result, err := Convert(input, format)
	if err != nil {
		return map[string]interface{}{ErrorFieldName: err.Error()}
	}
	return func() js.Value {
		arr := js.Global().Get("Uint8Array").New(len(result))
		js.CopyBytesToJS(arr, result)
		return arr
	}()
}

