// Code generated by enum-generator. DO NOT EDIT.

package config

func (v BlockSplitMode) Valid() bool {
	switch v {
	case "estimated", "exact":
		return true
	}
	return false
}

func (v StereoMode) Valid() bool {
	switch v {
	case "independent", "adaptive", "exhaustive":
		return true
	}
	return false
}

func (v OrderSearchMode) Valid() bool {
	switch v {
	case "estimated", "exhaustive":
		return true
	}
	return false
}

func (v RiceCostMode) Valid() bool {
	switch v {
	case "estimated", "exact":
		return true
	}
	return false
}
